### ISSUE TITLE
Performance bad on showcase PCs

### ISSUE THREAD

**Issue by SirNootNoot** [ungodlyaura/KillerCooking#18]
Describe the bug
Game test had like 40fps and screen tearing

Version
V5

To Reproduce
Can bring a test build to the room during/after class if available

**Comment by ungodlyaura** [comment]
i will attempt removing more OnTick's

**Comment by ungodlyaura** [comment]
i lowered quality on lighting stuff, game should be maybe 30%+ faster. also lower resolution if fps still issue

**Comment by ungodlyaura** [comment]
lower tri count on level2 food crates
lower tri count on characters

**Comment by SirNootNoot** [comment]
most texture LODs changed, from 1024x to 256x. Change in memory from ~1MB to 43kb

**Comment by SirNootNoot** [comment]
reduced polys on oven+stove (~10k), poison rack -80%, eye ~-5k, cheese -2k, mushroom -1k, crates -10k+, lamp -50%. and baked lights lvl 3. Will test performance tomorrow

**Comment by SirNootNoot** [comment]
some lights werent baked properly, still not quite 60fps on the test pc. However the showcase pc a laptop instead, so need to test on a different machine.

**Comment by SirNootNoot** [comment]
tris halved or more for almost everything, should be much better now. Other settings i can think of is graphics / lighting stuff, but idk how to do that, will see how it runs with these changes.

**Comment by SirNootNoot** [comment]
runs great on laptop
