### ISSUE TITLE
mothman invisible in cloak

### ISSUE THREAD

**Issue by SirNootNoot** [ungodlyaura/KillerCooking#20]
Bug:
With cloak accessory, mothman not showing. and maybe with other no_ears mothman things

Screenshot
![image](https://github.com/user-attachments/assets/59aa4ae1-6157-43e8-8b31-d1f4096289f0)

**Comment by ungodlyaura** [comment]
model was changed with bad anchor point 
![image](https://github.com/user-attachments/assets/2cc70bda-c450-49ef-a80b-89e2c9e591c8)

**Comment by Brycicle96** [comment]
![Screenshot 2024-10-27 094029](https://github.com/user-attachments/assets/4d9fcbc7-777c-4d08-9581-16b7d98b05da)
anchor point fixed
