### ISSUE TITLE
dialogue and accessories not matching

### ISSUE THREAD

**Issue by SirNootNoot** [ungodlyaura/KillerCooking#24]
Bug:
Dialogue not matching accessory, dialogue seems to be lined up to the target.

Screenshots
Sheriff hat with emo text
![Screenshot_9](https://github.com/user-attachments/assets/b3119135-2673-4e52-bea4-6cd8ae3390d3)

Sheriff hat with royal text. Kill description is country folk - I lost health from serving unpoisoned dish.
![Screenshot_13](https://github.com/user-attachments/assets/1ee1db73-6e06-413b-9bba-4f50dd575e97)

No accessory
![image](https://github.com/user-attachments/assets/97fb606a-8f5b-4bdd-9867-9b4f937cdad2)

**Comment by SirNootNoot** [comment]
More testing:
None of the sports text show accessories
Slime with jester dialogue shows emo accessories

**Comment by ungodlyaura** [comment]
Holy this guy doesn't read the king dialogue
